spring:
  datasource:
    firstdb:
      xa-properties:
        URL: jdbc:mysql://127.0.0.1:3306/firstdb
        user: root
        password: 1234
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: 'firstdb'
      min-pool-size: 5
      max-pool-size: 10
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    seconddb:
      xa-properties:
        URL: jdbc:mysql://127.0.0.1:3306/seconddb
        user: root
        password: 1234
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: 'seconddb'
      min-pool-size: 5
      max-pool-size: 10
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  logging:
    level:
      com:
        atomikos: INFO
        atomikos.icatch: INFO
        atomikos.jdbc: INFO
